# Generated by Django 2.0.9 on 2018-11-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nit', models.CharField(blank=True, max_length=20, null=True)),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=20)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(blank=True, max_length=200, null=True)),
                ('Dpi', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=20)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=130)),
                ('Tipo_Menu', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Refaccion', 'Refaccion'), ('Cena', 'Cena')], default='Desayuno', max_length=10)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=130)),
                ('Precio', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comida',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Menu'),
        ),
        migrations.AddField(
            model_name='comida',
            name='Plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Plato'),
        ),
    ]
